services:
  main-db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ms_network

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - rabbitmq
      - main
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  main:
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      target: development
    command: npm run start:dev main
    ports:
      - '3001:3001'
    env_file:
      - ./apps/main/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

volumes:
  pg_data:
  
networks:
  ms_network: